public class Loadout
{
    public int Counter { get; set; }
    public DateTime? TodaysDate { get; set; }
    public DateTime? LoadoutDatetime { get; set; }
    public int? OrderNumber { get; set; }
    public double? NIRMoisture { get; set; }
    public double? NIRProtein { get; set; }
    public int? NIRAlveoP { get; set; }
    public int? NIRAlveoW { get; set; }
    public double? NIRAsh { get; set; }
    public double? NIRFat { get; set; }
    public double? NIRFiber { get; set; }
    public double? StdMoisture { get; set; }
    public double? StdProtein { get; set; }
    public int? StdAlveoP { get; set; }
    public int? StdAlveoW { get; set; }
    public double? StdAsh { get; set; }
    public double? StdIron { get; set; }
    public double? pH { get; set; }
    public double? Over35 { get; set; }
    public double? Over20 { get; set; }
    public double? Over60 { get; set; }
    public double? Over70 { get; set; }
    public double? Over100 { get; set; }
    public double? Thru70 { get; set; }
    public double? Thru100 { get; set; }
    public int? CookieW { get; set; }
    public double? CookieT { get; set; }
    public double? MTI { get; set; }
    public double? Stab { get; set; }
    public double? Abs { get; set; }
    public string Vomitoxin { get; set; }
    public string Disposition { get; set; }
    public string COADisposition { get; set; }
    public string WhoAR { get; set; }
    public double? LacticAcid { get; set; }
    public bool? Fumigated { get; set; }
    public string NIRID { get; set; }
    public DateTime? ShipDate { get; set; }
    public bool? Hold { get; set; }
    public bool? Transload { get; set; }
    public bool? Shipped { get; set; }
    public string Comments { get; set; }
    public DateTime? LoadDate { get; set; }
    public int? LoadoutNumber { get; set; }
    public string Available { get; set; }
    public double? LacticAcidValue { get; set; }
    public double? Water { get; set; }
}