public class OrderDetail
{
    public int OrderNumber { get; set; }
    public DateTime? CreateDate { get; set; }
    public string ContractNumber { get; set; }
    public string BakeryID { get; set; }
    public int? BakeryIDNumber { get; set; }
    public string ReleaseNumber { get; set; }
    public DateTime? OrderDate { get; set; }
    public string VehicleNumber { get; set; }
    public string ShippedFrom { get; set; }
    public DateTime? ShipWeek { get; set; }
    public DateTime? DeliveryDate { get; set; }
    public DateTime? DeliveryTime { get; set; }
    public DateTime? ShipDate { get; set; }
    public DateTime? AccountingDate { get; set; }
    public string ClientComment { get; set; }
    public string InternalComment { get; set; }
    public string WhosEquipment { get; set; }
    public double? OriginWeight { get; set; }
    public int? DestinationWeight { get; set; }
    public string WhosWeight { get; set; }
    public decimal? Price { get; set; }
    public decimal? Freight { get; set; }
    public decimal? TEACFreight { get; set; }
    public decimal? AddlFreight { get; set; }
    public string Per { get; set; }
    public string BulkOrBagged { get; set; }
    public decimal? SackingCharges { get; set; }
    public decimal? SpottingCharge { get; set; }
    public decimal? Fumigation { get; set; }
    public DateTime? FreightDate { get; set; }
    public string WaybillFreightNumber { get; set; }
    public DateTime? FreightDateForAddlCharges { get; set; }
    public string AddlWaybillFreightNumber { get; set; }
    public int? AcctPeriod { get; set; }
    public string Carrier { get; set; }
    public string RouteID { get; set; }
    public int? RoutingID { get; set; }
    public int? InvoiceAddressID { get; set; }
    public string InvoiceNumber { get; set; }
    public DateTime? InvoiceDate { get; set; }
    public string WeekRequest { get; set; }
    public string BuyersPONumber { get; set; }
    public decimal? Vomitoxin { get; set; }
    public decimal? ProcessingFee { get; set; }
    public decimal? RRLease { get; set; }
    public bool? TrafficHold { get; set; }
    public bool? ShowHide { get; set; }
    public decimal? CarCleaning { get; set; }
    public int? NumberOfPallets { get; set; }
    public decimal? CostPerPallet { get; set; }
    public int? NumberOfBags { get; set; }
    public decimal? CostPerBag { get; set; }
    public DateTime? PickUpDate { get; set; }
    public DateTime? Delivery_Date { get; set; }
    public string PrimaryLotNumber { get; set; }
    public string SecondaryLotNumber { get; set; }
    public int? EDIPatternID { get; set; }
    public bool? EDIShipment { get; set; }
    public string EDIFileName { get; set; }
}