public class SealsUsed
{
    public int ID { get; set; }
    public string SealDate { get; set; }
    public string SealTime { get; set; }
    public string Seal01 { get; set; }
    public string Seal02 { get; set; }
    public string Seal03 { get; set; }
    public string Seal04 { get; set; }
    public string Seal05 { get; set; }
    public string Seal06 { get; set; }
    public string Seal07 { get; set; }
    public string Seal08 { get; set; }
    public string Seal09 { get; set; }
    public string Seal10 { get; set; }
    public string Seal11 { get; set; }
    public string Seal12 { get; set; }
    public string Seal13 { get; set; }
    public string Seal14 { get; set; }
    public string Seal15 { get; set; }
    public string Seal16 { get; set; }
    public string Seal17 { get; set; }
    public string Seal18 { get; set; }
    public string Seal19 { get; set; }
    public string Seal20 { get; set; }
    public string Seal21 { get; set; }
    public string Seal22 { get; set; }
    public string Seal23 { get; set; }
    public string Seal24 { get; set; }
    public string Seal25 { get; set; }
    public string Seal26 { get; set; }
    public string Seal27 { get; set; }
    public string Seal28 { get; set; }
    public string Seal29 { get; set; }
    public string Seal30 { get; set; }
    public string Seal31 { get; set; }
    public string Seal32 { get; set; }
    public string Seal33 { get; set; }
    public string Seal34 { get; set; }
    public string Seal35 { get; set; }
    public string Seal36 { get; set; }
    public string Seal37 { get; set; }
    public string Seal38 { get; set; }
    public string Seal39 { get; set; }
    public string Seal40 { get; set; }
    public string OrderNumber { get; set; }
    public string VehicleNumber { get; set; }
    public DateTime? DateTime { get; set; }
    public string ProductGrade { get; set; }
    public int? IntOrderNumber { get; set; }
    public DateTime? LastUpdate { get; set; }
}
